### ISSUE TITLE
When should we add pystac v1.0 support?

### ISSUE THREAD

**Issue by gadomski** [stac-utils/stactools#133]
As we work towards a stable v0.2 release of `stactools`, we should decide if this release should include updating `stactools` to support `pystac` v1.0. Here's the [pystac v1.0 milestone](https://github.com/stac-utils/pystac/milestone/20) for reference.

Arguments for:
- We're going to want to support `pystac` v1.0 as soon as possible, because people want to use `stactools` to update existing catalogs to STAC 1.0.
- We're already making some big changes, so why not throw it all in at once?
- If we don't include `pystac` 1.0 support in `stactools` 0.2, we'll need to release `stactools` v0.3 with pystac `1.0` support relatively soon therafter. This would mean that we'd have to minor releases right on top of each other (not really sure how bad this is).

Arguments against:
- All current core packages depend on `pystac` v0.5, and updating them to the new extension regime will take some work. It's kind of nice right now that the `stactools` v0.2 changes don't actually modify much actual code, mostly just packaging and plumbing.
- By breaking apart the reorganization and the `pystac` 1.0 support into discrete steps and versions, we're more clearly communicating our development workflow and allowing people to pick the version that they'd like (e.g. if they have a dataset package that needs `pystac~=0.5`, they would have a `stactools~=0.2` to depend upon).

Thoughts?

**EDIT**: For reference, here's the pull request that tried to add pystac 1.0 support to stactools v0.1: https://github.com/stac-utils/stactools/pull/113. It was blocked by failing tests in a dataset package, which was some of the reasoning behind breaking things apart in v0.2 in the first place. That PR can give a sense of how much work the upgrade is -- not a ton, but there is a chance to introduce errors.

**Comment by cholmes** [comment]
I'm for using 1.0 asap. Imho no one wants to make non-1.0.0 catalogs, and it's weird to have a 'new stac release', but have it only support 1.0.0-beta.2 (and I'm actually realizing right now that this was the source of my confusion yesterday. I wasn't thinking, but I pip installed the latest packages and thought I did something wrong because I was making beta.2 catalogs, forgetting I was doing the 1.0 catalogs on a branch).

With the new regime it seems like it can be ok if some of the extensions lag in their 1.0 upgrade? Like I'd say lets get the core out asap, and then if some extensions lag a bit / aren't released asap that's ok.

**Comment by gadomski** [comment]
FYSA I've updated https://github.com/stac-utils/stactools/pull/113 for the stactools reorganization, so we have a pull request ready to go if we do want to include PySTAC v1.0 support in stactools v0.2.
