### ISSUE TITLE
Docker push appears to be broken

### ISSUE THREAD

**Issue by gadomski** [stac-utils/stactools#181]
**Describe the bug**
https://github.com/stac-utils/stactools/pull/180/checks?check_run_id=3158676044#step:5:1080

@cuttlefish I don't know much about this, could this be ephemeral or is something misconfigured?

**Comment by cuttlefish** [comment]
@gadomski I think the issue here is that the dependabot user doesn't have write permissions on the repo (although somehow it can create branches?). It worked after I approved it, so I think an approval by someone with write perms grants those to the PR. Let's hold off and see if the same happens on the next couple PRs to verify.
