### ISSUE TITLE
Add to conda-forge

### ISSUE THREAD

**Issue by gadomski** [stac-utils/stactools#188]
It's another good way to allow folks to use stactools.

Requested by @mrsiegfried: https://twitter.com/grumplesiggy/status/1420747632620670984

**Comment by geomatician** [comment]
Stactools needs to have stac-check and stac-validator added to conda-forge first since it depends on them, and stac-check needs stac-validator as well. Therefore, I have submitted a PR to get stac-validator added to conda-forge first, which when approved will then allow us to also add stac-check and stactools packages.

**Comment by geomatician** [comment]
This PR can be closed. `Stactools` was added to `conda-forge`: see [](https://github.com/conda-forge/staged-recipes/pull/19297) and [](https://anaconda.org/conda-forge/stactools)
