### ISSUE TITLE
Add proj:shape and proj:transform to Planet output

### ISSUE THREAD

**Issue by cholmes** [stac-utils/stactools#39]
It'd be good to include the proj:shape and proj:transform fields in planet data output. Planet's columns plus origin_x and origin_y communiate the same information. I believe/hope we could get the shape and transform from those values (though how to do so is beyond me). If not then perhaps we could look at the planet data referenced, and/or I can work to get Planet to add it to their data api.

**Comment by matthewhanson** [comment]
That is enough, along with the resolution to construct the affine transform.  Since images are (almost always) north up, it simplifies to:
[ resolution, 0, origin_x, 0, -resolution, origin_y]

You'll notice in the S2 data (https://earth-search.aws.element84.com/v0/collections/sentinel-s2-l2a-cogs/items/S2A_18SVF_20210115_0_L2A) there's actually 9 elements in the array (3x3 matrix) because it's accounting for 3 dimensions, but the last row is just "0 0 1".  rasterio includes in when getting the transform via "src.transform"
